name: Build and test the VDA5050 library

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  industrial_ci:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        distro: [humble, jazzy]
        test_type: [gcc, clang]
        include:
          - {distro: jazzy, test_type: gcc-asan}
          - {distro: jazzy, test_type: gcc-tsan}
    env:
      ISOLATION: "shell"
      UPSTREAM_WORKSPACE: 'github:ros-industrial/vda5050_interfaces#main github:eclipse-paho/paho.mqtt.cpp#v1.5.0'
      ROS_DISTRO: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.distro }}-ros-core
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update -qq -y
          apt-get install libpaho-mqtt-dev libpaho-mqttpp-dev mosquitto -qq -y
      - name: Start MQTT broker
        run: |
          mosquitto -d
          sleep 2  # Wait for broker to start

      # GCC
      - if: ${{ matrix.test_type == 'gcc' }}
        uses: 'ros-industrial/industrial_ci@master'
        env:
          TARGET_CMAKE_ARGS: '-DENABLE_ROS2=ON'

      # GCC with address sanitizer
      - if: ${{ matrix.test_type == 'gcc-asan' }}
        uses: 'ros-industrial/industrial_ci@master'
        env:
          TARGET_CMAKE_ARGS: '-DENABLE_ROS2=ON -DCMAKE_C_FLAGS="-fsanitize=address -O1 -g -fno-omit-frame-pointer" -DCMAKE_CXX_FLAGS="-fsanitize=address -O1 -g -fno-omit-frame-pointer"'

      # GCC with thread sanitizer
      - if: ${{ matrix.test_type == 'gcc-tsan' }}
        uses: 'ros-industrial/industrial_ci@master'
        env:
          TARGET_CMAKE_ARGS: '-DENABLE_ROS2=ON -DCMAKE_C_FLAGS="-fsanitize=thread -O2 -g -fno-omit-frame-pointer" -DCMAKE_CXX_FLAGS="-fsanitize=thread -O2 -g -fno-omit-frame-pointer"'

      # Clang
      - if: ${{ matrix.test_type == 'clang' }}
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ADDITIONAL_DEBS: clang lld
          CC: "clang"
          CXX: "clang++"
          TARGET_CMAKE_ARGS: '-DENABLE_ROS2=ON'
